// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bynkmgayguubkkoeusej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5bmttZ2F5Z3V1Ymtrb2V1c2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDUxMjgsImV4cCI6MjA3Mjg4MTEyOH0.AUHngYQgU30pdITiGtiH_pu4xYKEbIH9l3RMv3gCFB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});